let date  = new Date()
console.log(date)
console.log("toISOString()  <======>   "+date.toISOString())
console.log("toUTCString()  <======>   "+date.toUTCString())
console.log("toJSON()  <======>   "+date.toJSON())
console.log("toDateString()  <======>   "+date.toDateString())
console.log("toTimeString()  <======>   "+date.toTimeString())
console.log("toLocaleTimeString()  <======>   "+date.toLocaleTimeString())
console.log("getTimezoneOffset()  <======>   "+date.getTimezoneOffset())